[package]
name = "iw-tectonics"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
iw-core.workspace = true
iw-mesh.workspace = true
glam.workspace = true
rand.workspace = true
rand_pcg.workspace = true
rustc-hash.workspace = true
rayon.workspace = true
smallvec.workspace = true
log.workspace = true
