[package]
name = "iw-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
iw-core.workspace = true
iw-mesh.workspace = true
iw-sim.workspace = true
iw-render-vulkan.workspace = true
anyhow.workspace = true
log.workspace = true
env_logger.workspace = true
clap.workspace = true
glam.workspace = true
